name: sample workflow
on:
  workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hi github action"
      - name: print goodbye
        run: echo "bye github action"
       
